# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-18 04:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSessionStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('session_key', models.CharField(db_index=True, max_length=40, unique=True)),
                ('ip_addr', models.CharField(blank=True, max_length=120, null=True)),
                ('max_sessions', models.IntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_stores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
